export const skillLists = [
  "Technology",
  "Programming",
  "Business",
  "Design",
  "Languages",
  "Health",
  "Personal Development",
  "Lifestyle",
  "Arts",
  "Finance",
  "Marketing",
  "Sales",
  "Engineering",
  "Music",
  "Photography",
  "Writing",
  "Cooking",
  "Sports",
  "Education",
  "Psychology",
  "History",
  "Politics",
  "Philosophy",
  "Travel",
  "Gaming",
  "Environmental Studies",
  "Crafts",
  "Entrepreneurship",
]

